language: node_js
node_js:
  - "6"

before_install:
  cd ./lab_01/app

install:
  - npm install

script: node node_modules/jshint/bin/jshint app.js

  deploy:
    provider: heroku
    app: rsoiapp
    api_key:
      secure: 16b0bce8-ac6b-4cc1-aa6f-7260db6dabc9
    strategy: git